### ISSUE TITLE
Locale-specific month names may cause test failures

### ISSUE THREAD

**Issue by eserte** [simbabque/Dancer2-Logger-Console-Colored#1]
Currently `t/logger_console_colored.t` fails if running under a German locale (e.g. `LC_ALL=de_DE.UTF-8`):
```
#   Failed test 'regression gh-11: %t works'
#   at t/logger_console_colored.t line 188.
#                   'Wide character in print at /opt/perl-5.28.0/lib/site_perl/5.28.0/Dancer2/Logger/Console.pm line 10.
# 16/M�r/2019 14:14:38
# '
#     doesn't match '(?^x:
#         ^                       # there is no color for the date by default
#         \d+/[a-zA-Z]+/\d{4}     # date
#         \s                      # whitespace
#         \d\d:\d\d:\d\d          # time
#         $
#     )'
# Looks like you failed 1 test of 24.
t/logger_console_colored.t ..
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/24 subtests
```
Currently, because March is "März" in German, the only month name with a non-ascii character.

**Comment by simbabque** [comment]
The Testers report looks like it's double or triple encoded. That's weird.

I've followed this up with the Dancer folk. I can get it to work with de_DE an other locales where I can fix the regex, but if I do ko_KR or ru_RU, it blows up without an error.  I've created https://stackoverflow.com/q/55240390/1331451 to get someone smarten than me to explain what's going on here. We've spotted a bug in Dancer2 that I've cargo-culted in this module.

I'll push a fix for the immediate problem, but leave this ticket open.
