### ISSUE TITLE
Suggestion: add link to the Advent Calendar article

### ISSUE THREAD

**Issue by cxw42** [simbabque/Dancer2-Logger-Console-Colored#2]
Thanks for this module!  I just discovered it through the [Advent Calendar article](http://advent.perldancer.org/2018/23).  May I suggest adding that link to the README, or using it as the repo's Web site?

Chris White (CXW)

**Comment by simbabque** [comment]
Thank you, that's a good idea. I should have thought of that in the first place. Github is a bit flaky right now, I will release this change later.
